version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/flowconfig
    docker:
    - image: circleci/php:7.1-cli-browsers-legacy
      environment:
        APP_ENV: test
    steps:
    - checkout
    - run:
        name: Install project dependencies
        command: composer install
    - run:
        name: Run Code Sniffer
        command: vendor/bin/phpcs
    - run:
        name: Run Unit tests
        command: vendor/bin/phpunit --log-junit build/phpunit/junit.xml --coverage-clover build/phpunit/coverage.xml
    - store_test_results:
        path: build
    - store_artifacts:
        path: build/phpunit/coverage.xml
    - codecov/upload:
        file: build/phpunit/coverage.xml
